"""Traced silhouettes of the original Chrome Glass frames.

traced.json (regenerated by trace.py from src/ai) holds, per cursor frame,
the simplified outline polygons. hybrid.py renders them as crisp anti-aliased
masks that carry the original's own translucency at every size.
"""
import json, math, os

HERE = os.path.dirname(os.path.abspath(__file__))
TRACED = json.load(open(os.path.join(HERE, "traced.json")))

SMOOTH_KEEP_DEG = 55     # corners turning more than this stay sharp when smoothing


def smooth(poly, iters=2):
    """Laplacian smoothing that keeps genuinely sharp corners (arrow tips)
    while melting the staircase left by polygon tracing.

    Points traced with a corner flag (x, y, is_corner) trust that flag - it
    was computed from the dense pre-simplification boundary chain, which is
    far less noise-prone than a single 3-point angle on an already-simplified
    polygon. Legacy 2-tuples (e.g. HELP_EXTRA's hand-authored polyline) fall
    back to the old local-angle threshold test."""
    if len(poly) < 5:
        return [(p[0], p[1]) for p in poly]
    flagged = [len(p) > 2 for p in poly]
    pts = [(p[0], p[1]) for p in poly]
    for _ in range(iters):
        n = len(pts)
        out = []
        for i in range(n):
            p0, p, p1 = pts[(i - 1) % n], pts[i], pts[(i + 1) % n]
            if flagged[i]:
                is_corner = poly[i][2]
            else:
                a1 = math.atan2(p[1] - p0[1], p[0] - p0[0])
                a2 = math.atan2(p1[1] - p[1], p1[0] - p[0])
                turn = abs((a2 - a1 + math.pi) % (2 * math.pi) - math.pi)
                is_corner = turn > math.radians(SMOOTH_KEEP_DEG)
            if is_corner:
                out.append(p)                      # real corner - keep it crisp
            else:
                out.append((0.5 * p[0] + 0.25 * p0[0] + 0.25 * p1[0],
                            0.5 * p[1] + 0.25 * p0[1] + 0.25 * p1[1]))
        pts = out
    return pts


# the "?" dot of Help is a separate 10-pixel island the original draws outside
# the arrow silhouette (centre (19,26.2) in the 2006 frame, x=18..20 y=25..28);
# trace.py keeps only the arrow body and drops it, so it is hand-authored here.
# It must sit at its real island coordinates - placed inside the arrow it renders
# invisible, since the mask there is already opaque from the arrow polygon.
#
# The curl itself is NOT hand-drawn: it used to be a stroked polyline here, but
# that line sat above and right of the real curl (its top ran through y=7..8
# where the 2006 frame is empty), so once the AI alpha master made the glass
# crisp it read as a second, ghost "?" over the true one. The AI alpha now holds
# the real curl on its own, so the line is gone and the ghost with it.
HELP_EXTRA = [
    {"dot": (19.0, 26.2, 1.1), "fill": (255, 255, 255, 255)},
]
