"""Traced silhouettes of the original Chrome Glass frames.

traced.json (regenerated by trace.py from src/ai) holds, per cursor frame,
the simplified outline polygons. hybrid.py renders them as crisp anti-aliased
masks that carry the original's own translucency at every size.
"""
import json, math, os

HERE = os.path.dirname(os.path.abspath(__file__))
TRACED = json.load(open(os.path.join(HERE, "traced.json")))

SMOOTH_KEEP_DEG = 55     # corners turning more than this stay sharp when smoothing
CORNER_HOLD = 2          # vertices either side of a corner held on its edge ray


def _corner_anchors(pts, corners, n):
    """For every vertex within CORNER_HOLD steps of a corner: (corner index,
    unit direction from that corner to the vertex), taken from the polygon
    before any smoothing so the ray cannot drift over the iterations."""
    anchors = {}
    for c in corners:
        for step in range(1, CORNER_HOLD + 1):
            for i in ((c + step) % n, (c - step) % n):
                if i in corners or i in anchors:
                    continue
                dx, dy = pts[i][0] - pts[c][0], pts[i][1] - pts[c][1]
                d = math.hypot(dx, dy)
                if d > 1e-9:
                    anchors[i] = (c, dx / d, dy / d)
    return anchors


def smooth(poly, iters=2):
    """Laplacian smoothing that keeps genuinely sharp corners (arrow tips)
    while melting the staircase left by polygon tracing.

    Points traced with a corner flag (x, y, is_corner) trust that flag - it
    was computed from the dense pre-simplification boundary chain, which is
    far less noise-prone than a single 3-point angle on an already-simplified
    polygon. Legacy 2-tuples fall
    back to the old local-angle threshold test.

    Keeping the corner itself crisp is not enough: averaging its neighbours
    pulls them sideways off the edge, which dents the silhouette right behind
    the point and blunts it again. The CORNER_HOLD vertices either side of a
    corner are therefore projected back onto the corner's own edge ray after
    each pass - they may still slide along the edge (which is what melts the
    staircase) but can no longer leave it."""
    if len(poly) < 5:
        return [(p[0], p[1]) for p in poly]
    flagged = [len(p) > 2 for p in poly]
    pts = [(p[0], p[1]) for p in poly]
    n = len(pts)
    corner = []
    for i in range(n):
        if flagged[i]:
            corner.append(bool(poly[i][2]))
        else:
            p0, p, p1 = pts[(i - 1) % n], pts[i], pts[(i + 1) % n]
            a1 = math.atan2(p[1] - p0[1], p[0] - p0[0])
            a2 = math.atan2(p1[1] - p[1], p1[0] - p[0])
            turn = abs((a2 - a1 + math.pi) % (2 * math.pi) - math.pi)
            corner.append(turn > math.radians(SMOOTH_KEEP_DEG))
    anchors = _corner_anchors(pts, {i for i in range(n) if corner[i]}, n)
    for _ in range(iters):
        out = []
        for i in range(n):
            p0, p, p1 = pts[(i - 1) % n], pts[i], pts[(i + 1) % n]
            if corner[i]:
                out.append(p)                      # real corner - keep it crisp
                continue
            q = (0.5 * p[0] + 0.25 * p0[0] + 0.25 * p1[0],
                 0.5 * p[1] + 0.25 * p0[1] + 0.25 * p1[1])
            if i in anchors:
                c, ux, uy = anchors[i]
                ax, ay = pts[c]
                t = (q[0] - ax) * ux + (q[1] - ay) * uy
                q = (ax + t * ux, ay + t * uy)     # back onto the edge ray
            out.append(q)
        pts = out
    return pts


# the "?" dot of Help is a separate 10-pixel island the original draws outside
# the arrow silhouette (centre (19,26.2) in the 2006 frame, x=18..20 y=25..28);
# trace.py keeps only the arrow body and drops it, so it is hand-authored here.
# It must sit at its real island coordinates - placed inside the arrow it renders
# invisible, since the mask there is already opaque from the arrow polygon.
#
# The curl itself is NOT hand-drawn: it used to be a stroked polyline here, but
# that line sat above and right of the real curl (its top ran through y=7..8
# where the 2006 frame is empty), so once the AI alpha master made the glass
# crisp it read as a second, ghost "?" over the true one. The AI alpha now holds
# the real curl on its own, so the line is gone and the ghost with it.
def _round_island(poly):
    """A traced island turned into the circle it is trying to be.

    Help's "?" dot comes back from the trace as a nine-vertex island - at 32px
    that is a circle, at 512 it is a visible octagon, and the hand-authored
    circle that used to be added beside it only made the two shapes stack and
    show each other's corners. Centre and area are the author's; only the
    corners go."""
    pts = [(float(q[0]), float(q[1])) for q in poly]
    n = len(pts)
    a = cx = cy = 0.0
    for k in range(n):
        x0, y0 = pts[k]
        x1, y1 = pts[(k + 1) % n]
        cr = x0 * y1 - x1 * y0
        a += cr
        cx += (x0 + x1) * cr
        cy += (y0 + y1) * cr
    a *= 0.5
    if abs(a) < 1e-9:
        return None
    cx, cy = cx / (6.0 * a), cy / (6.0 * a)
    return cx, cy, (abs(a) / math.pi) ** 0.5


# The dot under Help's "?" is an island of its own in the trace, and _mask
# renders it as a circle instead of as the polygon (see _round_island). The
# curl itself is not drawn at all: it used to be a stroked polyline here, but
# that line sat above and right of the real curl (its top ran through y=7..8
# where the 2006 frame is empty), so once the AI alpha master made the glass
# crisp it read as a second, ghost "?" over the true one. The AI alpha holds
# the real curl on its own, so the line is gone and the ghost with it.
HELP_ROUND_ISLANDS = {"Help"}
